### ISSUE TITLE
can you make a discord.py version?(suggestion)

### ISSUE THREAD

**Issue by HyperCodec** [Skotizo/VirusTotalBot#2]
I would really like to add this feature to my bot, but my bot is coded with python. Can you pls make a python version or tell me how to do it?

**Comment by The-Bow-Hunter** [comment]
I just published one, if you still need it. it is still in alpha but if you want to see it just check out [my Repository.](https://github.com/The-Bow-Hunter/VirusTotalDiscordBot)

**Comment by HyperCodec** [comment]
Ok thx!
